const STORAGE_KEY='fnf_movies_v16';
const VOTE_KEY='fnf_votes_v16';
let movies=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');
let myVotes=new Set(JSON.parse(localStorage.getItem(VOTE_KEY)||'[]'));
const grid=document.querySelector('#movies');
const apiKey=window.FNF_CONFIG?.TMDB_API_KEY||'';
const doubanSearch=m=>`https://search.douban.com/movie/subject_search?search_text=${encodeURIComponent(`${m.title} ${m.year||''}`)}&cat=1002`;
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(movies));localStorage.setItem(VOTE_KEY,JSON.stringify([...myVotes]))}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function movieKey(m){return String(m.tmdb_id||m.id)}
function render(){
  grid.innerHTML='';
  if(!movies.length){grid.innerHTML=`<div class="empty"><span>NO NOMINATIONS YET</span><h3>Be the first to<br><em>pick a film.</em></h3><p>The ballot is empty. Add something brilliant, questionable, or both.</p><button id="emptyAdd">+ Suggest the first movie</button></div>`;document.querySelector('#emptyAdd').onclick=()=>modal.showModal();return}
  movies.sort((a,b)=>b.votes-a.votes).forEach((m,i)=>{let el=document.createElement('article');el.className='movie';let link=doubanSearch(m),key=movieKey(m),voted=myVotes.has(key);el.innerHTML=`<div class="poster-wrap"><a class="poster-link" href="${link}" target="_blank" rel="noopener" title="Find ${esc(m.title)} on Douban"><div class="poster">${m.poster?`<img src="${esc(m.poster)}" alt="${esc(m.title)} poster">`:esc(m.title)}<span class="douban">豆瓣 ↗</span></div></a><button class="delete" data-i="${i}" aria-label="Delete ${esc(m.title)}">×</button></div><a class="title-link" href="${link}" target="_blank" rel="noopener"><h3>${esc(m.title)}</h3></a><div class="meta">${esc(m.year||'—')} · ${esc(m.genre||'Film')}</div><div class="by">Suggested by ${esc(m.by)}</div><p class="reason">“${esc(m.reason)}”</p><button class="vote ${voted?'voted':''}" data-i="${i}" ${voted?'disabled':''}>${voted?'♥':'♡'} ${m.votes} vote${m.votes===1?'':'s'}</button>`;grid.appendChild(el)});
  document.querySelectorAll('.vote').forEach(b=>b.onclick=()=>{const m=movies[+b.dataset.i],key=movieKey(m);if(myVotes.has(key))return;m.votes++;myVotes.add(key);save();render()});
  document.querySelectorAll('.delete').forEach(b=>b.onclick=()=>{const m=movies[+b.dataset.i];if(confirm(`Remove “${m.title}” from this week's ballot?`)){myVotes.delete(movieKey(m));movies.splice(+b.dataset.i,1);save();render()}})
}
render();
const now=new Date(),fri=new Date(now);fri.setDate(now.getDate()+((5-now.getDay()+7)%7));document.querySelector('#date').textContent=fri.toLocaleDateString('en-SG',{weekday:'long',day:'2-digit',month:'long'}).toUpperCase();
const modal=document.querySelector('#modal'),form=document.querySelector('#form'),search=document.querySelector('#movieSearch'),results=document.querySelector('#results'),status=document.querySelector('#searchStatus');
document.querySelector('#open').onclick=()=>modal.showModal();document.querySelector('#close').onclick=()=>modal.close();document.querySelector('#searchBtn').onclick=()=>{const q=search.value.trim();resetSelection();results.innerHTML='';if(q.length<2){status.textContent='Type at least 2 characters.';return;}findMovies(q)};
let timer;search.addEventListener('input',()=>{clearTimeout(timer);resetSelection();const q=search.value.trim();if(q.length<2){results.innerHTML='';status.textContent='';return}timer=setTimeout(()=>findMovies(q),350)});
function resetSelection(){['tmdb_id','title','year','poster','genre'].forEach(n=>{if(form.elements[n])form.elements[n].value=''})}
async function findMovies(q){if(!apiKey){status.innerHTML='TMDB search needs your API key in <b>config.js</b>.';return}status.textContent='Searching the projection booth…';try{const r=await fetch(`https://api.themoviedb.org/3/search/movie?api_key=${encodeURIComponent(apiKey)}&query=${encodeURIComponent(q)}&include_adult=false&language=en-US`);if(!r.ok)throw new Error(`TMDB returned ${r.status}`);const data=await r.json();status.textContent=data.results.length?'Choose the right film:':'No films found.';results.innerHTML=data.results.slice(0,6).map(m=>{const poster=m.poster_path?`https://image.tmdb.org/t/p/w500${m.poster_path}`:'';const year=(m.release_date||'').slice(0,4);return `<button type="button" class="result" data-id="${m.id}" data-title="${esc(m.title)}" data-year="${year}" data-poster="${poster}">${poster?`<img src="${poster}" alt="">`:`<span class="mini-poster">?</span>`}<span><strong>${esc(m.title)}</strong><small>${year||'Year unknown'}${m.original_title!==m.title?` · ${esc(m.original_title)}`:''}</small></span></button>`}).join('');document.querySelectorAll('.result').forEach(b=>b.onclick=()=>selectMovie(b))}catch(e){console.error(e);status.textContent=`TMDB search error: ${e.message}`;results.innerHTML=''}}
async function selectMovie(b){form.elements.tmdb_id.value=b.dataset.id;form.elements.title.value=b.dataset.title;form.elements.year.value=b.dataset.year;form.elements.poster.value=b.dataset.poster;search.value=`${b.dataset.title}${b.dataset.year?` (${b.dataset.year})`:''}`;results.innerHTML='';status.textContent='Loading movie details…';try{const r=await fetch(`https://api.themoviedb.org/3/movie/${encodeURIComponent(b.dataset.id)}?api_key=${encodeURIComponent(apiKey)}&language=en-US`);if(r.ok){const d=await r.json();form.elements.genre.value=(d.genres||[]).slice(0,3).map(g=>g.name).join(' · ')}}catch(e){}status.textContent='✓ Movie selected — poster & genres ready.'}
form.onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);if(!f.get('title')){status.textContent='Please search and select a movie first.';return}if(movies.some(m=>String(m.tmdb_id)===String(f.get('tmdb_id')))){status.textContent='That movie is already on this week’s ballot.';return}movies.push({id:crypto.randomUUID(),tmdb_id:+f.get('tmdb_id'),title:f.get('title'),year:f.get('year'),genre:f.get('genre')||'Film',by:f.get('name'),reason:f.get('reason'),votes:0,poster:f.get('poster')});save();render();e.target.reset();results.innerHTML='';status.textContent='';modal.close()};
