const cfg=window.FNF_CONFIG||{};
const apiKey=cfg.TMDB_API_KEY||'';
const db=window.supabase?.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_KEY);
const VOTER_KEY='fnf_voter_v2';
let voterId=localStorage.getItem(VOTER_KEY);
if(!voterId){voterId=crypto.randomUUID();localStorage.setItem(VOTER_KEY,voterId)}
let movies=[], votes=[];
const grid=document.querySelector('#movies'),syncStatus=document.querySelector('#syncStatus');
const doubanSearch=m=>`https://search.douban.com/movie/subject_search?search_text=${encodeURIComponent(`${m.title} ${m.release_year||''}`)}&cat=1002`;
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function voteCount(id){return votes.filter(v=>v.movie_id===id).length}
function hasVoted(id){return votes.some(v=>v.movie_id===id&&v.voter_id===voterId)}
function render(){
 grid.innerHTML='';
 const candidates=movies.filter(m=>m.status==='candidate').sort((a,b)=>voteCount(b.id)-voteCount(a.id));
 if(!candidates.length){grid.innerHTML=`<div class="empty"><span>NO NOMINATIONS YET</span><h3>Be the first to<br><em>pick a film.</em></h3><p>The ballot is empty. Add something brilliant, questionable, or both.</p><button id="emptyAdd">+ Suggest the first movie</button></div>`;document.querySelector('#emptyAdd').onclick=()=>modal.showModal();return}
 candidates.forEach(m=>{const count=voteCount(m.id),voted=hasVoted(m.id),link=doubanSearch(m),el=document.createElement('article');el.className='movie';el.innerHTML=`<div class="poster-wrap"><a class="poster-link" href="${link}" target="_blank" rel="noopener"><div class="poster">${m.poster_url?`<img src="${esc(m.poster_url)}" alt="${esc(m.title)} poster">`:esc(m.title)}<span class="douban">豆瓣 ↗</span></div></a><button class="delete" data-id="${m.id}" aria-label="Delete">×</button></div><a class="title-link" href="${link}" target="_blank" rel="noopener"><h3>${esc(m.title)}</h3></a><div class="meta">${esc(m.release_year||'—')} · ${esc(m.genres||'Film')}</div><div class="by">Suggested by ${esc(m.submitted_by)}</div><p class="reason">“${esc(m.reason)}”</p><button class="vote ${voted?'voted':''}" data-id="${m.id}" ${voted?'disabled':''}>${voted?'♥':'♡'} ${count} vote${count===1?'':'s'}</button>`;grid.appendChild(el)});
 document.querySelectorAll('.vote').forEach(b=>b.onclick=()=>castVote(b.dataset.id));
 document.querySelectorAll('.delete').forEach(b=>b.onclick=()=>removeMovie(b.dataset.id));
}
async function loadAll(show=true){if(!db){syncStatus.textContent='Supabase is not configured.';return}if(show)syncStatus.textContent='Syncing the ballot…';const [mr,vr]=await Promise.all([db.from('movies').select('*'),db.from('votes').select('*')]);if(mr.error||vr.error){syncStatus.textContent=`Database setup needed: ${(mr.error||vr.error).message}`;return}movies=mr.data||[];votes=vr.data||[];syncStatus.textContent='';render()}
async function castVote(movieId){const {error}=await db.from('votes').insert({movie_id:movieId,voter_id:voterId});if(error){if(error.code==='23505')return;alert(`Vote failed: ${error.message}`)}await loadAll(false)}
async function removeMovie(id){const m=movies.find(x=>x.id===id);if(!confirm(`Remove “${m?.title||'this movie'}” from this week's ballot?`))return;const {error}=await db.from('movies').delete().eq('id',id);if(error)alert(`Delete failed: ${error.message}`);await loadAll(false)}
const now=new Date(),fri=new Date(now);fri.setDate(now.getDate()+((5-now.getDay()+7)%7));document.querySelector('#date').textContent=fri.toLocaleDateString('en-SG',{weekday:'long',day:'2-digit',month:'long'}).toUpperCase();
const modal=document.querySelector('#modal'),form=document.querySelector('#form'),search=document.querySelector('#movieSearch'),results=document.querySelector('#results'),status=document.querySelector('#searchStatus');
document.querySelector('#open').onclick=()=>modal.showModal();document.querySelector('#close').onclick=()=>modal.close();document.querySelector('#searchBtn').onclick=()=>{const q=search.value.trim();resetSelection();results.innerHTML='';if(q.length<2){status.textContent='Type at least 2 characters.';return}findMovies(q)};
let timer;search.addEventListener('input',()=>{clearTimeout(timer);resetSelection();const q=search.value.trim();if(q.length<2){results.innerHTML='';status.textContent='';return}timer=setTimeout(()=>findMovies(q),350)});
function resetSelection(){['tmdb_id','title','year','poster','genre'].forEach(n=>{if(form.elements[n])form.elements[n].value=''})}
async function findMovies(q){if(!apiKey){status.textContent='TMDB key missing.';return}status.textContent='Searching the projection booth…';try{const r=await fetch(`https://api.themoviedb.org/3/search/movie?api_key=${encodeURIComponent(apiKey)}&query=${encodeURIComponent(q)}&include_adult=false&language=en-US`);if(!r.ok)throw new Error(`TMDB returned ${r.status}`);const data=await r.json();status.textContent=data.results.length?'Choose the right film:':'No films found.';results.innerHTML=data.results.slice(0,6).map(m=>{const poster=m.poster_path?`https://image.tmdb.org/t/p/w500${m.poster_path}`:'';const year=(m.release_date||'').slice(0,4);return `<button type="button" class="result" data-id="${m.id}" data-title="${esc(m.title)}" data-year="${year}" data-poster="${poster}">${poster?`<img src="${poster}" alt="">`:`<span class="mini-poster">?</span>`}<span><strong>${esc(m.title)}</strong><small>${year||'Year unknown'}${m.original_title!==m.title?` · ${esc(m.original_title)}`:''}</small></span></button>`}).join('');document.querySelectorAll('.result').forEach(b=>b.onclick=()=>selectMovie(b))}catch(e){status.textContent=`TMDB search error: ${e.message}`;results.innerHTML=''}}
async function selectMovie(b){form.elements.tmdb_id.value=b.dataset.id;form.elements.title.value=b.dataset.title;form.elements.year.value=b.dataset.year;form.elements.poster.value=b.dataset.poster;search.value=`${b.dataset.title}${b.dataset.year?` (${b.dataset.year})`:''}`;results.innerHTML='';status.textContent='Loading movie details…';try{const r=await fetch(`https://api.themoviedb.org/3/movie/${b.dataset.id}?api_key=${encodeURIComponent(apiKey)}&language=en-US`);if(r.ok){const d=await r.json();form.elements.genre.value=(d.genres||[]).slice(0,3).map(g=>g.name).join(' · ')}}catch(e){}status.textContent='✓ Movie selected — poster & genres ready.'}
form.onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);if(!f.get('title')){status.textContent='Please search and select a movie first.';return}const payload={tmdb_id:+f.get('tmdb_id'),title:f.get('title'),release_year:+f.get('year')||null,poster_url:f.get('poster'),genres:f.get('genre')||'Film',submitted_by:f.get('name'),reason:f.get('reason'),status:'candidate'};status.textContent='Adding to the shared ballot…';const {error}=await db.from('movies').insert(payload);if(error){status.textContent=error.code==='23505'?'That movie is already on this week’s ballot.':`Could not add movie: ${error.message}`;return}e.target.reset();results.innerHTML='';status.textContent='';modal.close();await loadAll(false)};
if(db){db.channel('fnf-live').on('postgres_changes',{event:'*',schema:'public',table:'movies'},()=>loadAll(false)).on('postgres_changes',{event:'*',schema:'public',table:'votes'},()=>loadAll(false)).subscribe()}
loadAll();
